# permissions for end users to edit certificatemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: certificatemonitor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: check-certs
    app.kubernetes.io/part-of: check-certs
    app.kubernetes.io/managed-by: kustomize
  name: certificatemonitor-editor-role
rules:
- apiGroups:
  - monitoring.egarciam.com
  resources:
  - certificatemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.egarciam.com
  resources:
  - certificatemonitors/status
  verbs:
  - get
