---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.egarciam.com
  resources:
  - certificatemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.egarciam.com
  resources:
  - certificatemonitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.egarciam.com
  resources:
  - certificatemonitors/status
  verbs:
  - get
  - patch
  - update
