apiVersion: monitoring.egarciam.com/v1alpha1
kind: CertificateMonitor
metadata:
  labels:
    app.kubernetes.io/name: certificatemonitor
    app.kubernetes.io/instance: certificatemonitor-sample
    app.kubernetes.io/part-of: check-certs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: check-certs
  name: certificatemonitor-sample
spec:
  # TODO(user): Add fields here
  discoverInternal: true
  sendMail: true
